apiVersion: v1
kind: Service
metadata:
  name: vrms-user-service
spec:
  type: NodePort
  selector:
    app: vrms-user-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
